### PR TITLE
[Canvas worker] Fix initial canvas size to prevent blur & fix resize event

### LINKED ISSUE #2781: [Canvas worker] Animation is blurry & resize event doesn't work
Hey! I'm trying to use canvas worker and struggled to do it without passing my own offscreen canvas [here (codesandbox)](https://codesandbox.io/s/bold-field-l5yeph?file=/index.js).
The problem is the size of canvas is seting by its json props, but we ignore the container size

### PR DESCRIPTION
**Pull request by knenkne**
Fix #2781 
I think we've to prioritize `container`'s size over `animationData`'s size, otherwise the initial animation will be blurry

The real problem is that `updateContainerSize` does not work correctly with worker at the moment, but this commit will fix an initial view. 
I've been actively exploring a core logic and trying to fix `resize` method lately, seems like we need to override some methods from CanvasRenderer. 
Would be great to get some advices about it @bodymovin

### CODE REVIEW

**Comment by RobMeyer** [comment]
This looks good to me, and taking it a step further I wonder if the container should be observed using ResizeObserver so that the offscreen canvas can automatically be resized without requiring clients to call animationItem.resize() manually.

I also see that CanvasRendererBase.prototype.updateContainerSize includes a lot more logic to take the preserveAspectRatio into account. Should that code be factored out and reused here, or is it unnecessary during initialization? I'm not entirely sure how all these classes relate to each other.

**Comment by knenkne** [comment]
So here we go. Video preview is [here](https://www.youtube.com/watch?v=cMriZw3hi6Y). 

The things we do:
1. Create `rollup` build with monkey patched methods (they can now work inside `Worker`'s thread correctly
2. Get this build and wrap it with `module`
3. Pass `width` and `height` with `dpr` multiplier via `message`
4. Change `canvas` size from `Worker`'s thread

The things we can improve:
1. Create Worker's module from scratch and not monkey patch methods (with custom `CanvasRenderer` and `AnimationItem` at least) - seems like a big task for sure
2. Monkey patch some more methods such like `configAnimation` to save correct `dpr` at least (now it's always `1`), the good thing right here is that by doing so, we'll gradually get a step closer to complete the first point (a bigger task)

I'm ready to help to discuss and improve things @bodymovin 
Thanks!

**Comment by knenkne** [comment]
Hey @bodymovin!
Would be glad to hear any updates/suggestions, I'm free to dicscuss and help on this one

File: player/js/worker_wrapper.js [hunk 1]
```diff
@@ -687,10 +687,14 @@ var lottie = (function () {
         });
       },
       resize: function () {
+        var devicePixelRatio = window.devicePixelRatio || 1;
         workerInstance.postMessage({
           type: 'resize',
           payload: {
             id: animationId,
+            // Till Worker thread knows nothing about container, we've to pass it here
+            width: animation.container.offsetWidth * devicePixelRatio,
```
Comment (bodymovin) [inline player/js/worker_wrapper.js:696]: animation.container could be undefined.
what about changing it to:
`width: width || (animation.container ? animation.container.offsetWidth * devicePixelRatio : 0),
height: height || (animation.container ? animation.container.offsetHeight * devicePixelRatio : 0),
`  
and letting the resize method accept 2 arguments `width` and `height`?

File: player/js/modules/canvas_worker.js [hunk 2]
```diff
@@ -0,0 +1,80 @@
+import lottie from './canvas';
```
Comment (bodymovin) [inline player/js/modules/canvas_worker.js:1]: this file is not used anymore

**Comment by bodymovin** [comment]
Hey, thanks for this. Sorry for the delay.
I added a couple of comments. In addition to those, AnimationItem's resize method, should probably become:
player\js\animation\AnimationItem.js
```js
AnimationItem.prototype.resize = function (width, height) {
  this.renderer.updateContainerSize(width, height);
};
```

File: player/js/worker_wrapper.js (hunk 1 above)
Comment (knenkne) [reply player/js/worker_wrapper.js:696]: > animation.container could be undefined. what about changing it to: `width: width || (animation.container ? animation.container.offsetWidth * devicePixelRatio : 0), height: height || (animation.container ? animation.container.offsetHeight * devicePixelRatio : 0), ` and letting the resize method accept 2 arguments `width` and `height`?

Yeah, It should definitely accept `width` and `height` as params

File: player/js/modules/canvas_worker.js [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+import AnimationItem from '../animation/AnimationItem';
+import CanvasRenderer from '../renderers/CanvasRenderer';
+
+// Monkey patch some methods to work correctly with Worker
+AnimationItem.prototype.resize = function (width, height) {
+  this.renderer.updateContainerSize(width, height);
+};
+
+CanvasRenderer.prototype.updateContainerSize = function (width, height) {
```
[the remark this answers is not in the document]
Comment (knenkne) [reply player/js/modules/canvas_worker.js:10]: > this could be moved to `player\js\renderers\CanvasRendererBase.js` lines 208 and 209
> 
> ```js
>     elementWidth = width || this.canvasContext.canvas.width * this.renderConfig.dpr;
>     elementHeight = height || this.canvasContext.canvas.height * this.renderConfig.dpr;
> ```

Yeah, sounds good, the monkey patching was a temporary decision before getting in touch with you. Perfect that we can extend it right here

**Comment by knenkne** [comment]
> Hey, thanks for this. Sorry for the delay. I added a couple of comments. In addition to those, AnimationItem's resize method, should probably become: player\js\animation\AnimationItem.js
> 
> ```js
> AnimationItem.prototype.resize = function (width, height) {
>   this.renderer.updateContainerSize(width, height);
> };
> ```
> 
> what do you think?

Yeah, that's more efficient and easy to support code against monkey patching. 🙊 
So I'll remove it and also new canvas module w/ rollup build. 
Thanks for your review, will push changes soon 🚀

**Comment by knenkne** [comment]
@bodymovin  Hey! It's been a while 😄
